creytiv/re

mk/re.mk, src/main/openssl.c
Minimal changes required to build and use `libre` on DragonFly BSD.  It is a followup to PR #6.
=> Add support for DragonFly BSD

include/re_tls.h, src/tls/openssl/tls_udp.c
These changes add the possibility to get and set the DTLS connection's remote peer address.
To make this possible, the following functions have been added:
```c
const struct sa *dtls_peer(const struct tls_conn *tc);
void dtls_set_peer(struct tls_conn *tc, const struct sa *peer);
```
=> Change DTLS connection's remote peer address

include/re_tls.h, src/tls/openssl/tls.c
These changes give the user a little bit more fine granularity when setting a certificate (and the private key).
Other private key types than RSA are now supported.
PEM certificate and private key can now be contained in separate strings.
Moreover, the user is able to use the DER format for certificates and private keys.
To make this possible, the following functions have been added:
- `tls_set_certificate_pem`
- `tls_set_certificate_der`
- for compatibility, `tls_set_certificate` has been updated and uses `tls_set_certificate_pem` underneath
No changes to existing function signatures had to be made. :)
(Rebased and fixed version as a replacement for #15)
=> Setting Certificate/Private Key Improvements

mk/re.mk
this PR adds two new makefile rules for making a tarball from GIT projects
that include `re.mk`
* make git_release -- create a release tarball from a version tag (e.g. `v0.5.0`)
* make git_snapshot -- create a tarball from the current HEAD version.
@richaas please review and merge to master
=> mk: rules for making tarball (ref #31)

src/tls/openssl/tls.c
this fixes https://github.com/creytiv/re/issues/32
another solution is to swap the inclusion of openssl and re header files,
as this would include windows headers first and then openssl headers
after that.
=> tls: undef X509_NAME for win32 (fixes #32)

Makefile, README.md, debian/changelog, debian/copyright, docs/COPYING, docs/ChangeLog, rpm/re.spec
I would like to make a new release of libre version 0.5.1
the release date has been set to Saturday 4. Feb 2017
using retest and baresip the following platforms have been tested:
- Android NDK r13 (api 17)
- Arch Linux
- CentOS 7.3 x86_64
- Debian 6.0 i386
- Debian 7.11 x86_64
- Debian 8.7 i386
- Fedora 24 x86_64
- MacOSX v10.12 x86_64
- Mingw32 (Debian 7)
- OpenBSD 6.0 (amd64)
- Ubuntu 14.04 x86_64
- Ubuntu 16.04 x86_64
The following compilers have been tested with:
- clang 8.0.0
- gcc 4.2.1
- gcc 4.4.5
- gcc 4.7.2	
- gcc 4.8.4
- gcc 4.8.5	
- gcc 4.9.2
- gcc 4.9	
- gcc 5.4.0
- gcc 6.3.1
The following versions of OpenSSL has been tested with:
- OpenSSL 0.9.8o
- OpenSSL 1.0.1e-fips
- OpenSSL 1.0.1f
- OpenSSL 1.0.1t
- OpenSSL 1.0.2g
- OpenSSL 1.0.2j
- OpenSSL 1.0.2j-fips
- OpenSSL 1.1.0c
- …
=> update changelog for libre 0.5.1

src/srtp/srtcp.c
the ep is left-shifted by 31-bits. If the size of int
is 4 bytes then the EP bit will end up in the top bit
which is also the sign bit.
it is safer and better to use an unsigned type here
=> srtcp: use unsigned 32-bit for encrypted bit

README.md, src/main/main.c
- Remove special case for SOLARIS
- Tested on Solaris 11.3 with gcc
ref https://github.com/creytiv/re/pull/22
@richaas please review and merge to master
=> Solaris pthread once

include/re_telev.h, src/telev/telev.c
For telephone events the same timestamp base as for audio is used. Thus the correct clock rate also has to
be taken into account for calculation of durations and needs to be configurable.
=> Make sampling rate for telephone events configurable

include/re_mod.h, src/mod/mod.c
it is needed by e.g. baresip to traverse all modules and check
for specific name/type
please review and merge to master.
/Alfred
=> mod: add accessor function to module list

include/re_sipreg.h, src/sipreg/reg.c
Add accessor function in order to expose the IP address used in the Contact header URI  when registering. The same SIP URI will appear as the request URI of incoming requests.
@alfredh please review and merge
=> sipreg: add accessor function sipreg_laddr()

include/re_ice.h, src/ice/cand.c, src/ice/chklist.c
Also added a function to get the type of a candidate. This can be used when
sending data to handle relay candidates, where data must be sent through the
TURN client.
This is a more flexible variant of what I did in #71.
=> ice: Added functions to get selected candidates.

mk/re.mk
In Debian 9 (stretch), the ar program in the binutils package is now configured with
`--enable-deterministic-archives`. This make deterministic default mode, opposite of previous behavior. When running ar on Debian 9 we then get the following warning:
```
CC      build-x86_64/json/decode_odict.o
CC      build-x86_64/json/encode.o
LD      libre.so
AR      libre.a
ar: `u' modifier ignored since `D' is the default (see `U')
```
This PR make ar always use deterministic mode (on linux). This change makes the archives reproducible; equal input will always result in binary equal archive. The alternative would be to add the `U` option and thus keep the old, non-deterministic behavior.
@alfredh, please review and commit.
=> Update ar flags; use deterministic mode

include/re_odict.h, src/odict/entry.c
building libre with clang 3.9 gives a warning in odict:
```
$ make CC=clang-mp-3.9 
CC      build-x86_64/odict/entry.o
src/odict/entry.c:60:15: warning: passing an object that undergoes default argument promotion to
'va_start' has undefined behavior [-Wvarargs]
va_start(ap, type);
^
src/odict/entry.c:41:23: note: parameter of type 'enum odict_type' is declared here
enum odict_type type, ...)
^
1 warning generated.
```
It looks like the Github Travis build servers have changed to clang 3.9
so the building of libre is currently failing.
most of the vararg code in libre is using a pointer (e.g. const char *) or
`uint32_t` and this code does not give warnings.
perhaps there are other solutions?
=> odict: use int instead of enum to avoid vararg promotion

mk/re.mk
It turns out that we need both debian/.debhelper and debian/*.debhelper
=> make target debclean: update to reflect recent debhelper changes

src/mqueue/mqueue.c
Without the change, the `data` field is padded to the next 8 bytes boundary on 64 bit systems, resulting in `sizeof(struct msg)` to be 24 bytes and valgrind reporting uninitialized bytes:
```
==22350== Syscall param write(buf) points to uninitialised byte(s)
==22350==    at 0x5CB734D: ??? (syscall-template.S:81)
==22350==    by 0x948EFE: pipe_write (mqueue.h:21)
==22350==    by 0x949157: mqueue_push (mqueue.c:152)
```
After reordering the fields, the struct size is 16 bytes and no padding is required.
=> Pack struct of mqueue messages.

include/re_tls.h, src/tls/openssl/tls_udp.c
The current DTLS module only supports receiving packets on the UDP socket.
There is a usecase where an incoming DTLS packet will arrive on a different type
of socket. If TURN over TCP/TLS is used for the media transport, the DTLS packets
will be sent/recv via a TCP socket.
If ICE is used as media transport, with both UDP-based and TCP-based candidates,
the DTLS module must be able to receive packets on both of them.
@richaas please review and merge to master
=> tls: add dtls_recv_packet()

include/re_http.h, src/http/chunk.c, src/http/client.c, src/http/http.h, src/http/mod.mk, src/http/msg.c, src/http/server.c, src/websock/websock.c
This PR adds support for chunked transfer encoding in the HTTP client. This transfer encoding is quite common, and support for this is mandatory in [HTTP/1.1](https://tools.ietf.org/html/rfc7230#section-4.1). @alfredh please test, review and merge to master.
=> http: added support for chunked transfer encoding

src/tls/openssl/tls.c, src/tls/openssl/tls.h, src/tls/openssl/tls_tcp.c, src/tls/openssl/tls_udp.c
This PR fixes the reported issue #92.
@alfredh, please test, review and merge.
I was not able to reproduce the restund issue on Debian stable (openssl 1.1.0f-3), so please verify with your Debian testing environment.
=> tls: use per connection bio_method (fixes issue #92)

include/re_net.h, mk/re.mk, src/mod/dl.c, src/net/mod.mk, src/net/net.c, src/tcp/tcp.c, src/udp/udp.c
The Cygwin platform is not supported any more.
This PR removes the last remnants of cygwin support.
When compiling libre on Linux, the libre.a static library is binary equal
before/after this patch (symbols stripped with strip -s ):
```
md5sum libre*.a
18645b6f51594fa853d2f2ef05dae13a  libre.a
18645b6f51594fa853d2f2ef05dae13a  libre_ref.a
```
@richaas Please review and merge to master.
=> remove support for Cygwin

src/net/win32/wif.c
when compiling with mingw32 and running in wine emulator,
I get this error when enumerating network interfaces:
wif: if_list: GetAdaptersAddresses ret=111
use a large buffer for IP_ADAPTER_ADDRESSES fixes the error
this PR is another solution to this PR:
https://github.com/creytiv/re/pull/98
@richaas Please review and merge.
=> net: larger buffer for net_if_list

include/re_mem.h, src/mem/mod.mk, src/mem/secure.c
the use case for these functions is secure code like
SRTP and TLS.
memcmp() should not be used when comparing secret data
such as shared keys, because the content may affect the timing.
instead the compare function should always take the same
to execute, independently of the content.
=> mem: add secure memory functions

include/re_aes.h, src/aes/apple/aes.c, src/aes/openssl/aes.c, src/aes/stub.c
This patch adds support for AES GCM mode, using the OpenSSL backend.
The usecase is TLS and SRTP.
The GCM mode is of type AEAD and provides both encryption
and authentication (with a tag). This is different from e.g. CTR-mode which
only provides encryption.
The code is functional, and the API is a suggestion.
Design:
* Provide AAD via `aes_encr` and `aes_decr`
* Separate functions to get/verify authentication tag
Comparison of CTR and GCM modes:
|                 | AES CTR  | AES GCM  |
| --------------- | -------- | -------- |
| Encryption      | Yes      | Yes      |
| Authentication  | No       | Yes      |
| IV              | 16 bytes | 12 bytes |
| Tag length      | -        | 16 bytes |
Retest:
https://github.com/creytiv/retest/tree/aes_add_gcm
Alfred
=> aes: add support for GCM Galois Counter Mode

README.md, include/re_srtp.h, src/srtp/misc.c, src/srtp/replay.c, src/srtp/srtcp.c, src/srtp/srtp.c, src/srtp/srtp.h, src/srtp/stream.c
This PR adds support for AES-GCM cipher in the SRTP Stack, as defined
in https://tools.ietf.org/html/rfc7714
Retest: https://github.com/creytiv/retest/tree/srtp_add_gcm
Srtp performance test: https://github.com/alfredh/srtperf/tree/srtp_add_gcm
TODO list:
=> Srtp add gcm

mk/win32/re.vcxproj, mk/win32/re.vcxproj.filters, src/mqueue/mqueue.c
* Update MSVS15 project
* Deleted gather.c from project
=> Update Windows project

src/mqueue/mqueue.c
In order to avoid pipe "constipation", we need to set the read/write file descriptors in non-blocking mode. Otherwise write will block if pipe is full, and read will block if pipe is empty.
=> mqueue: set non-blocking mode for read/write file descriptors

src/tls/openssl/tls.c
this was added in OpenSSL 1.1.0 hence the ifdef check.
=> tls: add AES-GCM to DTLS-SRTP

include/re_types.h
See https://github.com/creytiv/re/issues/140. Tested on Visual Studio 2017, would be great if someone can test for older VC versions. This article https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/z8y1yy88(v=vs.120) indicates that even in old version, the inline was available for C++, only issue is with C code, because of pure historical support of C99. By the way this has changed and it now supports inline as well, so the commit could be improved by checking for specific version of _MSC_VER < X (I don't know minimal possible X though), but it is not needed.
=> Inline C++ issue fix for MSVC

src/net/if.c
there is a bug in the networking code where the wrong interface name
is picked when resolving from IP-address to Interface name.
this is because `sa_cmp` is checked for 0 instead of `true`.
@richaas please review and merge to master.
=> net: sa_cmp returns true for match

include/re_net.h
this API is old and unused, and should be removed.
@richaas please review and merge to master.
=> net: remove net_conn api (old and unused)

src/sip/transp.c
after calling tcp_connect(), the address returned by
tcp_conn_local_get() is 0.0.0.0 on some platforms (Windows).
the local address of the TCP-connection is not available
until the TCP connection is fully established, so fetch the
address again in the established handler.
Reference: https://github.com/alfredh/baresip/issues/431
=> sip: get local TCP address in establish handler

src/jbuf/jbuf.c
When a jitter buffer is flushed also the statistic data should be cleared. That
means set back to zero. Except the field n_flush should be incremented. This fixes ugly warnings like
"jbuf: get: seq=32373 too late"
when the stream is resumed.
=> jbuf: zero out jbuf_stat on jbuf flush

Makefile, debian/changelog, docs/ChangeLog, rpm/re.spec
This is a proposal to release libre version 0.5.9
Suggested release date is set to Saturday 1. September 2018
=> release 0.5.9

include/re_uri.h, src/rtmp/conn.c, src/uri/uri.c
this PR adds support for IPv6 uris.
after this PR the following URI types should be supported:
* IPv4 address
* IPv6 address
* FQDN domain name
Example URI:
* rtmp://example.com/vod/mp4:sample.mp4
* rtmp://127.0.0.1/vod/mp4:sample.mp4
* rtmp://[::1]/vod/mp4:sample.mp4
The IPv6 address must be encapsulated in square brackets `[]` similar
to other protocols such as SIP.
=> rtmp: handle both IPv4 and IPv6 uris

src/rtmp/dechunk.c
it is possible to receive an RTMP format 3 message after format 0,1,2 even if the
total payload is not fragmented.
```
Type 3 chunks have no message header.  The stream ID, message length
and timestamp delta fields are not present; chunks of this type take
values from the preceding chunk for the same Chunk Stream ID.  When a
single message is split into chunks, all chunks of a message except
the first one SHOULD use this type.  Refer to Example 2
(Section 5.3.2.2).  A stream consisting of messages of exactly the
same size, stream ID and spacing in time SHOULD use this type for all
chunks after a chunk of Type 2.  Refer to Example 1
(Section 5.3.2.1).  If the delta between the first message and the
second message is same as the timestamp of the first message, then a
chunk of Type 3 could …
```
=> Rtmp dechunk fix

src/rtmp/dechunk.c
if the RTMP packet received is not complete, the dechunker
will decode the RTMP header and then return (wait for more data).
currently it erroneously also updates the timestamp from the delta,
even if the packet is incomplete. this means that the timestamp
will be updated twice, which is not correct.
a suggested fix is to move the timestamp calculation to after the
complete packet has been read.
=> rtmp: update timestamp after complete packet

src/main/main.c
I've used `fd_listen` for a pipe a while ago and encountered that `EPOLLHUP` was not handled. This PR raises `FD_EXCEPT` in case the `EPOLLHUP` event is being catched.
I have since removed the code that used the pipe from my code but thought this might still be a useful addition.
=> Handle EPOLLHUP

include/re_rtmp.h, src/rtmp/conn.c
adds a new function to set the RTMP connection callback handlers.
@richaas please review and merge to master
=> rtmp: add function to set handlers

src/rtmp/dechunk.c, src/rtmp/hdr.c, src/rtmp/rtmp.h
=> rtmp: proper handling of extended timestamps (take 2)

Makefile
The library directory can be specified by user in LIBDIR but it was not reflected in libre.pc. This commit fixes this.
=> Fix libdir in pkgconfig

mk/win32/re.vcxproj, mk/win32/re.vcxproj.filters
Hello!
Recently, in commit 9ec2b170188bceac80c00bfd95ba78b99ce960b5 file `uri/ucmp.c` was removed. This PR removes it from build list in Visual Studio
=> Update MSVS project (Remove uri_cmp)

src/tls/openssl/tls_tcp.c
If a TLS closure alert is observed before all received data is handed to the application, the TCP connection is closed and the data is lost. In the proposed fix we ignore the SSL_ERROR_ZERO_RETURN error, and leave the connection open until closed at the TCP level.
=> tls: don't close connection on SSL_ERROR_ZERO_RETURN

mk/re.mk
=> Set SDK path (SYSROOT) using xcrun (fix building on macOS 10.14)

debian/rules, mk/re.mk
This patch also makes the debclean target redundant.
=> Automatic cleanup after building debian package

include/re_fmt.h, src/fmt/pl.c, src/rtmp/conn.c
change rtmp flash version and fix url parsing
=> Rtmp appinst
